---
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.39.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [prepare-commit-msg]
  - repo: https://github.com/abravalheri/validate-pyproject
    rev: v0.14
    hooks:
      - id: validate-pyproject