name: Create python project release PR

on:
  push:
    branches:
      - "test-gn"
permissions:
  contents: write
  pull-requests: write

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: python
          package-name: release-please-action
          prerelease: false
          extra-files: |
            "pyproject.toml"
          version-file: pyproject.toml

