name: Python Test Build

on:
  pull_request:
    branches:
      - "test*"
  push:
    branches-ignore:
      - "main"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }} 
      - name: Install Dependencies
        run: |
          python -m pip install pip-tools 
          python -m piptools compile --extra dev -o requirements.txt pyproject.toml
          pip install -r requirements.txt
      - name: flake8 Lint Source
        uses: py-actions/flake8@v2
        with:
          max-line-length: "120"
          path: "src"
      - name: flake8 Lint Tests
        uses: py-actions/flake8@v2
        with:
          max-line-length: "120"
          path: "test" 
      - name: Unit Tests
        run: |
          python3 -m unittest discover -s tests --verbose
      - name: Build
        run: |
          python3 -m build
      
